output: '/panfs/qcb-panasas/kavoss/simulations/'
partis: '/home1/kavoss/partis_with_simulation/partis/' #specifiy where partis is located
raxml: '/home1/kavoss/raxml-ng/' #specify where raxml is located
vquest: '/home1/kavoss/vquest' #specify where vquest is located
MPTP: '/home1/kavoss/mptp-0.2.4-linux-x86_64/bin/' #specifiy where mptp is located

